name: SSH Test
on: [workflow_dispatch]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 5.44.40.79
          username: jenkins
          key: ${{ secrets.SSH_KEY }}
          debug: true
          script: |
            whoami
            hostname
            uname -a