name: SSH Test
on: [workflow_dispatch]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami
            hostname
            uname -a